[package]
name = "actix-web-async-compat"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"
description = "Actix web 1.x async/await shim."
license = "MIT"

[dependencies]
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }